### ISSUE TITLE
1.15.1 Deploy and Release Checklist

### ISSUE THREAD

**Issue by PeterDSteinberg** [Binstar/binstar-build#268]
This is the TODO list as part of releasing and deploying anaconda-build 1.15.1.
#### PRs to merge

Fix anaconda-cluster-contrib's `salt-anaconda-builder` for a problems found in 1.15.0 deploy.  These two issues must be fixed for cluster deploy of docker workers:
- [ ] https://github.com/ContinuumIO/anaconda-cluster-contrib/issues/18 (Peter)
- [ ] https://github.com/ContinuumIO/anaconda-cluster-contrib/issues/19 (Peter)
- [ ] anaconda-platform/anaconda-server#2110 (Derek)
- [ ] https://github.com/Anaconda-Platform/anaconda-server/pull/2122
#### Deployment
- [ ] Get Distribution team to build conda package and promote repo.continuum.io
- [ ] Conduct beta testing session with internal stakeholders
- [ ] Product Manager - Book release meeting with support, IT, docs, marketing
- [ ] Post to @all in the main flow that updates are happening and when completed
- [ ] Change the ec2 provider credentials in anaconda-jumpbox's acluster configuration to point to production ec2 account not 'dev'.  This should involve just creating a new provider with the prod AWS key and secret. Make sure the new provider is mentioned in each of the cluster configs in `~/.acluster/profiles.d/`
